In [1]:
import pandas as pd 

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
df=pd.read_csv("fraud.csv")

In [6]:
df.head(10)

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815      170136.00       160296.36   
1     1   PAYMENT   1864.28  C1666544295       21249.00        19384.72   
2     1  TRANSFER    181.00  C1305486145         181.00            0.00   
3     1  CASH_OUT    181.00   C840083671         181.00            0.00   
4     1   PAYMENT  11668.14  C2048537720       41554.00        29885.86   
5     1   PAYMENT   7817.71    C90045638       53860.00        46042.29   
6     1   PAYMENT   7107.77   C154988899      183195.00       176087.23   
7     1   PAYMENT   7861.64  C1912850431      176087.23       168225.59   
8     1   PAYMENT   4024.36  C1265012928        2671.00            0.00   
9     1     DEBIT   5337.77   C712410124       41720.00        36382.23   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0            0.00        0               0  
1  M2044282225             0.0            0.00        0               0  
2   C553264065             0.0            0.00        1               0  
3    C38997010         21182.0            0.00        1               0  
4  M1230701703             0.0            0.00        0               0  
5   M573487274             0.0            0.00        0               0  
6   M408069119             0.0            0.00        0               0  
7   M633326333             0.0            0.00        0               0  
8  M1176932104             0.0            0.00        0               0  
9   C195600860         41898.0        40348.79        0               0

In [7]:
df.tail()

step      type      amount     nameOrig  oldbalanceOrg  \
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
6362615             0.0   C776919290            0.00       339682.13        1   
6362616             0.0  C1881841831            0.00            0.00        1   
6362617             0.0  C1365125890        68488.84      6379898.11        1   
6362618             0.0  C2080388513            0.00            0.00        1   
6362619             0.0   C873221189      6510099.11      7360101.63        1   

         isFlaggedFraud  
6362615               0  
6362616               0  
6362617               0  
6362618               0  
6362619               0

In [8]:
df.shape


(6362620, 11)

In [9]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [11]:
df.isFraud.unique()

array([0, 1])

In [12]:
df.type.unique()

array(['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN'],
      dtype=object)

In [13]:
df.isFlaggedFraud.unique()

array([0, 1])

In [14]:
numeric_df = df.select_dtypes(include='number')  # only numbers


In [15]:
numeric_df['type'] = df['type'].map({ 
    'PAYMENT': 0,
    'TRANSFER': 1,
    'CASH_OUT': 2,
    'DEBIT': 3,
    'CASH_IN': 4
})

In [16]:
corr= numeric_df.corr()

In [17]:
print(corr['isFraud'])

step              0.031578
amount            0.076688
oldbalanceOrg     0.010154
newbalanceOrig   -0.008148
oldbalanceDest   -0.005885
newbalanceDest    0.000535
isFraud           1.000000
isFlaggedFraud    0.044109
type             -0.004463
Name: isFraud, dtype: float64


In [18]:
df.drop('isFlaggedFraud',axis=1,inplace=True)

In [19]:
df.type.value_counts()

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 10 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
dtypes: float64(5), int64(2), object(3)
memory usage: 485.4+ MB


In [21]:
!pip install plotly



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [22]:
import plotly.express as px
import plotly.io as pio
type= df['type'].value_counts()
fig = px.pie(
    names=type.index,
    values=type.values,
    title="Distribution of transaction type"
)
fig.show()


In [23]:
df['type'] = df['type'].map({
    'PAYMENT': 0,
    'TRANSFER': 1,
    'CASH_OUT': 2,
    'DEBIT': 3,
    'CASH_IN': 4
})


In [24]:
df.head()

step  type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1     0   9839.64  C1231006815       170136.0       160296.36   
1     1     0   1864.28  C1666544295        21249.0        19384.72   
2     1     1    181.00  C1305486145          181.0            0.00   
3     1     2    181.00   C840083671          181.0            0.00   
4     1     0  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  
0  M1979787155             0.0             0.0        0  
1  M2044282225             0.0             0.0        0  
2   C553264065             0.0             0.0        1  
3    C38997010         21182.0             0.0        1  
4  M1230701703             0.0             0.0        0

In [25]:
print(df['type'].unique())


[0 1 2 3 4]


In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x=np.array(df[['step','type','amount','oldbalanceOrg','newbalanceOrig']])

In [28]:
y=np.array(df[['isFraud']])

In [29]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.10,random_state=22)

In [30]:
from sklearn.tree import DecisionTreeClassifier


model1 = DecisionTreeClassifier()


# Fit all models
model1.fit(x_train, y_train.ravel())




DecisionTreeClassifier()

In [31]:
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression(max_iter=1000)
model2.fit(x_train, y_train.ravel())

LogisticRegression(max_iter=1000)

In [32]:
print('decidiontree',model1.score(x_test,y_test))

decidiontree 0.9996998091980976


In [33]:
print('logisticregression',model2.score(x_test,y_test))

logisticregression 0.999240878757493


In [36]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred = model2.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    635467
           1       0.92      0.43      0.59       795

    accuracy                           1.00    636262
   macro avg       0.96      0.71      0.79    636262
weighted avg       1.00      1.00      1.00    636262



In [ ]:
# CAUGHT IN 4K classic imbalanced dataset behavior

In [37]:
y2_pred = model1.predict(x_test)
print(classification_report(y_test, y2_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    635467
           1       0.88      0.88      0.88       795

    accuracy                           1.00    636262
   macro avg       0.94      0.94      0.94    636262
weighted avg       1.00      1.00      1.00    636262



In [38]:
df.head()

step  type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1     0   9839.64  C1231006815       170136.0       160296.36   
1     1     0   1864.28  C1666544295        21249.0        19384.72   
2     1     1    181.00  C1305486145          181.0            0.00   
3     1     2    181.00   C840083671          181.0            0.00   
4     1     0  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  
0  M1979787155             0.0             0.0        0  
1  M2044282225             0.0             0.0        0  
2   C553264065             0.0             0.0        1  
3    C38997010         21182.0             0.0        1  
4  M1230701703             0.0             0.0        0

In [39]:
df.tail()

step  type      amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
6362615   743     2   339682.13   C786484425      339682.13             0.0   
6362616   743     1  6311409.28  C1529008245     6311409.28             0.0   
6362617   743     2  6311409.28  C1162922333     6311409.28             0.0   
6362618   743     1   850002.52  C1685995037      850002.52             0.0   
6362619   743     2   850002.52  C1280323807      850002.52             0.0   

            nameDest  oldbalanceDest  newbalanceDest  isFraud  
6362615   C776919290            0.00       339682.13        1  
6362616  C1881841831            0.00            0.00        1  
6362617  C1365125890        68488.84      6379898.11        1  
6362618  C2080388513            0.00            0.00        1  
6362619   C873221189      6510099.11      7360101.63        1

In [40]:
features=np.array([[1,0,9839.64,170136.0,160296.36]])

In [41]:
print(model1.predict(features))

[0]


In [42]:
features=np.array([[743,1,6311409.28,6311409.28,0.0]])
print(model1.predict(features))

[1]


In [43]:
features=np.array([[743,1,6311409.28,6311409.28,0.0]])
print(model2.predict(features))

[1]


In [44]:
features=np.array([[1,0,9839.64,170136.0,160296.36]])
print(model2.predict(features))

[0]
